{
 "title": "SNMP Exporter Internal Stats",
 "tags": [
  "prometheus",
  "internal"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job_exporter",
    "label": "Exporter Job",
    "query": "query_result(snmp_exporter_build_info)"
   },
   {
    "name": "instance_exporter",
    "label": "Exporter Instance",
    "query": "query_result(snmp_exporter_build_info{job=~\"$job_exporter\"})"
   },
   {
    "name": "job_target",
    "label": "Target Job",
    "query": "query_result(snmp_scrape_pdus_returned)"
   },
   {
    "name": "instance_target",
    "label": "Target Instance",
    "query": "query_result(snmp_scrape_pdus_returned{job=~\"$job_target\"})"
   },
   {
    "name": "interval",
    "query": "5m,10m,15m, 20m, 30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "at a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$job_exporter\",instance=\"$instance_exporter\"}[$interval]) * 100",
     "legendFormat": "$interval rate"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job_exporter\", instance=\"$instance_exporter\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "Uptime [$interval]",
   "type": "singlestat",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance_exporter\",job=~\"$job_exporter\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "singlestat",
   "description": "Sum of errors in requests to the SNMP exporter during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum_over_time(snmp_request_errors_total{job=~\"$job_exporter\", instance=~\"$instance_exporter\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Total PDUs returned",
   "type": "singlestat",
   "description": "Total PDUs returned across all selected target jobs and target instances. Averaged over the selected time period in Grafana.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(snmp_scrape_pdus_returned{job=~\"$job_target\", instance=~\"$instance_target\"})"
    }
   ]
  },
  {
   "title": "resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"$job_exporter\",instance=\"$instance_exporter\"}[$interval])",
       "legendFormat": "Irate"
      },
      {
       "expr": "rate(process_cpu_seconds_total{job=\"$job_exporter\",instance=\"$instance_exporter\"}[$interval])",
       "legendFormat": "$interval rate"
      }
     ]
    },
    {
     "title": "Resident Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job_exporter\", instance=\"$instance_exporter\"}",
       "legendFormat": "RSS"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"$job_exporter\", instance=\"$instance_exporter\"}",
       "legendFormat": "Next GC"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=\"$job_exporter\", instance=\"$instance_exporter\"}",
       "legendFormat": "Allocated"
      }
     ]
    }
   ]
  },
  {
   "title": "durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collection Duration, $interval rate",
     "type": "graph",
     "description": "Duration of collections by the SNMP exporter by module.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(snmp_collection_duration_seconds_sum{job=~\"$job_exporter\", instance=~\"$instance_exporter\"}[$interval])",
       "legendFormat": "{{ module }}"
      }
     ]
    },
    {
     "title": "Unexpected PDUs, $interval rate",
     "type": "graph",
     "description": "Unexpected Go types in a PDU.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(snmp_unexpected_pdu_type_total{job=\"$job_exporter\", instance=\"$instance_exporter\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Scrape Duration by Instance",
     "type": "graph",
     "description": "Sum of scrape durations for a specific instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (snmp_scrape_duration_seconds)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Scrape Duration by Job",
     "type": "graph",
     "description": "Sum of scrape durations for a specific job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (snmp_scrape_duration_seconds)",
       "legendFormat": "{{ job }}"
      }
     ]
    }
   ]
  },
  {
   "title": "walks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Walk Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "snmp_scrape_walk_duration_seconds{job=~\"$job_target\", instance=~\"$instance_target\"}",
       "legendFormat": "{{ instance }} [via {{ job }}]"
      }
     ]
    },
    {
     "title": "PDUs returned, $interval avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(snmp_scrape_pdus_returned{job=~\"$job_target\", instance=~\"$instance_target\"}[$interval])",
       "legendFormat": "{{instance}} [via {{job}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "build info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Build info",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "snmp_exporter_build_info{job=~\"$job_exporter\"}"
      }
     ]
    }
   ]
  }
 ]
}