{
 "title": "Telegraf Internal Stats",
 "tags": [ "internal" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "query_result(internal_agent_gather_errors)"
   },
   {
    "name": "instance",
    "query": "query_result(up{job=~\"$job\"})"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$interval]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "Telegraf Memory Usage in relation to total memory available",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"} * 100) / scalar(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "singlestat",
   "description": "Resident set memory size is number of memory pages the process has in real memory, with pagesize. This results in the amount of memory that belongs specifically to that process in bytes. This excludes swapped out memory pages.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Buffer Limit",
   "type": "singlestat",
   "description": "Current",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "internal_write_buffer_limit{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{output}}@{{instance}}"
    }
   ]
  },
  {
   "title": "Total Metrics Dropped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "internal_write_metrics_dropped{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average Metrics Gathered per Second",
   "type": "singlestat",
   "description": "Across all inputs",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (instance) (rate(internal_gather_metrics_gathered{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Average Metrics Gather Time",
   "type": "singlestat",
   "description": "Across all inputs",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "format": "ns",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg by (instance) (rate(internal_gather_gather_time_ns{job=~\"$job\", instance=~\"$instance\"}[30m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "Irate"
      },
      {
       "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "5m rate"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "RSS"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Next GC"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "Allocated"
      }
     ]
    }
   ]
  },
  {
   "title": "vsphere",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connect Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum by (vcenter) (internal_vsphere_connect_ns{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{vcenter}}"
      }
     ]
    },
    {
     "title": "Discover Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum by (vcenter) (internal_vsphere_discover_ns{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{vcenter}}"
      }
     ]
    },
    {
     "title": "Discovered Objects - Host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type, vcenter) (internal_vsphere_discovered_objects{job=~\"$job\", instance=~\"$instance\", type=\"host\"})",
       "legendFormat": "{{vcenter}}"
      }
     ]
    },
    {
     "title": "Discovered Objects - Datastores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (vcenter) (internal_vsphere_discovered_objects{job=~\"$job\", instance=~\"$instance\", type=\"datastore\"})",
       "legendFormat": "{{vcenter}} - {{type}}"
      }
     ]
    },
    {
     "title": "Gathers - Host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (vcenter) (internal_vsphere_gather_count{job=~\"$job\", instance=~\"$instance\", resourcetype=\"host\"})",
       "legendFormat": "{{vcenter}}"
      }
     ]
    },
    {
     "title": "Gathers - Datastore",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (vcenter) (internal_vsphere_gather_count{job=~\"$job\", instance=~\"$instance\", resourcetype=\"datastore\"})",
       "legendFormat": "{{vcenter}}"
      }
     ]
    },
    {
     "title": "Gather Time - Host",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum by (vcenter) (internal_vsphere_gather_duration_ns{job=~\"$job\", instance=~\"$instance\", resourcetype=\"host\"})",
       "legendFormat": "{{vcenter}}"
      }
     ]
    },
    {
     "title": "Gather Time - Datastore",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum by (vcenter) (internal_vsphere_gather_duration_ns{job=~\"$job\", instance=~\"$instance\", resourcetype=\"datastore\"})",
       "legendFormat": "{{vcenter}}"
      }
     ]
    }
   ]
  },
  {
   "title": "agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Gather Errors",
     "type": "stat",
     "description": "Across all input plugins",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "internal_agent_gather_errors{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Metrics Dropped",
     "type": "stat",
     "description": "Across all input plugins",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "internal_agent_metrics_dropped{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Gather Error Rate, $interval",
     "type": "graph",
     "description": "Across all input plugins",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Errors /s" }
     ],
     "targets": [
      {
       "expr": "rate(internal_agent_gather_errors{job=~\"$job\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metrics Dropped Rate, $interval",
     "type": "graph",
     "description": "Across all input plugins",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Dropped /s" }
     ],
     "targets": [
      {
       "expr": "rate(internal_agent_metrics_dropped{job=~\"$job\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Metrics Gathered per Second",
     "type": "graph",
     "description": "Across all input plugins",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(internal_agent_metrics_gathered{job=~\"$job\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Metrics Written per Second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(internal_agent_metrics_written{job=~\"$job\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gather",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gather Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "internal_gather_gather_time_ns{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{input}}"
      }
     ]
    },
    {
     "title": "Metrics Gathered per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(internal_gather_metrics_gathered[$interval])",
       "legendFormat": "{{input}}"
      }
     ]
    }
   ]
  },
  {
   "title": "write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Limit",
     "type": "graph",
     "description": "By output",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "internal_write_buffer_limit{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{output}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Buffer Size",
     "type": "graph",
     "description": "By output",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "internal_write_buffer_size{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{putput}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Metrics Dropped",
     "type": "graph",
     "description": "By output",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "internal_write_metrics_dropped{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{output}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Metrics Filtered",
     "type": "graph",
     "description": "By output",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "internal_write_metrics_filtered{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{output}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Metrics Added per Second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(internal_write_metrics_added{job=~\"$job\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metrics Written per Second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(internal_write_metrics_written{job=~\"$job\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Time",
     "type": "graph",
     "description": "By output",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "internal_write_write_time_ns{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{output}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Rate / 2m",
     "type": "graph",
     "description": "GC invocation durations",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}